# Generated by Django 5.1.3 on 2025-01-02 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_to', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='NONE', null=True)),
                ('verified_at', models.DateTimeField(blank=True, default='2000-12-18 09:06:21', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_cash_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, choices=[('fright_transportation', 'Fright/Transportation'), ('food_grocery', 'Food/Grocery'), ('fuel_oil', 'Fuel and Oil'), ('others', 'Others'), ('vendor', 'Vendor'), ('reimbursement', 'Reimbursement'), ('site_services', 'Site Services'), ('advances', 'Advances'), ('travelling', 'Travelling'), ('electricity_bill', 'Electricity Bill'), ('internet_bill', 'Internet Bill'), ('postage_telegram', 'Postage and Telegram'), ('machine_repair', 'Machine Repair and Maintenance'), ('conveyance', 'Conveyance'), ('stationary_printing', 'Stationary and Printing'), ('hospitality', 'Hospitality')], max_length=50, null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_option', models.CharField(choices=[('bill', 'Bill'), ('voucher', 'Voucher'), ('gst', 'GST')], max_length=20, null=True)),
                ('bill_photo', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('voucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_category', models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External')], max_length=100, null=True)),
                ('internal_option', models.CharField(blank=True, default='abs', max_length=100, null=True)),
                ('external_type', models.CharField(blank=True, default='legs', max_length=100, null=True)),
                ('gst_photo', models.ImageField(blank=True, null=True, upload_to='gst_photos/')),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card')], max_length=20, null=True)),
                ('proof_photo', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_details', models.TextField(blank=True, null=True)),
                ('evoucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('borrowed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('borrowed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
