# Generated by Django 4.2.17 on 2025-06-20 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conveyance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('2_wheeler', '2_Wheeler'), ('4_wheeler', '4_Wheeler')], max_length=20)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, choices=[('fright_transportation', 'Fright/Transportation'), ('food_grocery', 'Food/Grocery'), ('fuel_oil', 'Fuel and Oil'), ('others', 'Others'), ('vendor', 'Vendor'), ('reimbursement', 'Reimbursement'), ('site_services', 'Site Services'), ('advances', 'Advances'), ('travelling', 'Travelling'), ('electricity_bill', 'Electricity Bill'), ('internet_bill', 'Internet Bill'), ('postage_telegram', 'Postage and Telegram'), ('machine_repair', 'Machine Repair and Maintenance'), ('conveyance', 'Conveyance'), ('stationary_printing', 'Stationary and Printing'), ('hospitality', 'Hospitality')], max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_option', models.CharField(choices=[('bill', 'Bill'), ('voucher', 'Voucher'), ('gst', 'GST'), ('2_wheeler', '2-Wheeler'), ('4_wheeler', '4-Wheeler')], max_length=20, null=True)),
                ('bill_photo', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('voucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_category', models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External')], max_length=100, null=True)),
                ('internal_option', models.CharField(blank=True, default='abs', max_length=100, null=True)),
                ('external_type', models.CharField(blank=True, default='legs', max_length=100, null=True)),
                ('gst_photo', models.ImageField(blank=True, null=True, upload_to='gst_photos/')),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card')], max_length=20, null=True)),
                ('proof_photo', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_details', models.TextField(blank=True, null=True)),
                ('evoucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('is_draft', models.BooleanField(default=False)),
                ('km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('advance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.advancegroup')),
                ('conveyance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.conveyance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProofPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proofs/')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_photos', to='website.expense')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_to', models.CharField(max_length=25)),
                ('item_name', models.CharField(max_length=255)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='NONE', null=True)),
                ('verified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('proof_photo', models.FileField(blank=True, null=True, upload_to='cashvoucher_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_cash_vouchers', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.expense')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrowed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_amounts', to='website.expense')),
            ],
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.advancegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
    ]
