# Generated by Django 4.2.17 on 2025-06-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_expense_rejection_reason_alter_expense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
