# Generated by Django 4.2.17 on 2025-06-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_expense_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
