# Generated by Django 5.1.3 on 2025-01-02 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_expense_borrowed_amount_expense_borrowed_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='borrowed_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='borrowed_from',
        ),
        migrations.CreateModel(
            name='BorrowedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrowed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_entries', to='website.expense')),
            ],
        ),
    ]
