# Generated by Django 5.1.3 on 2025-01-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_expense_borrowed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedamount',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_amounts', to='website.expense'),
        ),
    ]
