# Generated by Django 4.2.17 on 2025-06-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_expense_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashvoucher',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_vouchers', to='website.expense'),
        ),
    ]
