# Generated by Django 4.2.17 on 2025-07-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
