# Generated by Django 5.1.3 on 2025-01-03 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_cashvoucher_expense_alter_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashvoucher',
            name='verified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
