# Generated by Django 4.2.17 on 2025-07-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_submitted_at_paymentrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='amount',
        ),
    ]
