# Generated by Django 5.1.3 on 2025-01-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_cashvoucher_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashvoucher',
            name='paid_to',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
