# Generated by Django 4.2.17 on 2025-07-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_paymentrequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequestmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
