# Generated by Django 5.1.3 on 2025-01-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_cashvoucher_paid_to_alter_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
