# Generated by Django 5.1.3 on 2025-01-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_expense_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashvoucher',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
