# Generated by Django 4.2.17 on 2025-07-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_paymentrequestmessage_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequestmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
