# Generated by Django 5.1.3 on 2025-01-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_cashvoucher_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('draft', 'Draft')], default='pending', max_length=20),
        ),
    ]
