# Generated by Django 4.2.17 on 2025-07-21 11:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_advancegroupupdatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancegroup',
            name='initial_advance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
