# Generated by Django 5.1.3 on 2025-01-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_expense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
