# Generated by Django 4.2.17 on 2025-07-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_advancegroup_initial_advance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancegroup',
            name='initial_advance',
        ),
    ]
