# Generated by Django 4.2.17 on 2025-07-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_advancegroup_initial_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancegroupupdatelog',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='advance_proofs/'),
        ),
    ]
