# Generated by Django 5.1.3 on 2025-01-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_expense_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
