# Generated by Django 4.2.17 on 2025-07-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_advancegroupupdatelog_proof_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='item_type',
            field=models.CharField(blank=True, choices=[('fright_transportation', 'Fright/Transportation'), ('food_grocery', 'Food/Grocery'), ('fuel_oil', 'Fuel and Oil'), ('others', 'Others'), ('vendor', 'Vendor'), ('reimbursement', 'Reimbursement'), ('site_services', 'Site Services'), ('advances', 'Advances'), ('travelling', 'Travelling'), ('electricity_bill', 'Electricity Bill'), ('internet_bill', 'Internet Bill'), ('postage_telegram', 'Postage and Telegram'), ('machine_repair', 'Machine Repair and Maintenance'), ('conveyance', 'Conveyance'), ('stationary_printing', 'Stationary and Printing'), ('hospitality', 'Hospitality'), ('medicine', 'Medicine')], max_length=50, null=True),
        ),
    ]
