# Generated by Django 4.2.17 on 2025-07-30 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_expense_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
            ],
        ),
    ]
