# Generated by Django 5.1.3 on 2025-01-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
