# Generated by Django 4.2.17 on 2025-07-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_api'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Api',
        ),
    ]
