# Generated by Django 4.2.17 on 2025-07-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_delete_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='delete_requested',
            field=models.BooleanField(default=False),
        ),
    ]
