# Generated by Django 5.1.3 on 2025-01-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_notification_status_notification_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conveyance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('two_wheeler', 'Two-Wheeler'), ('four_wheeler', 'Four-Wheeler')], max_length=20)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
