# Generated by Django 5.1.3 on 2025-01-20 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_conveyance_expense_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='conveyance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.conveyance'),
        ),
        migrations.AlterField(
            model_name='conveyance',
            name='vehicle_type',
            field=models.CharField(choices=[('2_wheeler', '2-Wheeler'), ('4_wheeler', '4-Wheeler')], max_length=20),
        ),
    ]
