# Generated by Django 5.1.3 on 2025-01-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_expense_conveyance_alter_conveyance_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='transaction_option',
            field=models.CharField(choices=[('bill', 'Bill'), ('voucher', 'Voucher'), ('gst', 'GST'), ('two-wheeler', 'Two-Wheeler'), ('four-wheeler', 'Four-Wheeler')], max_length=20, null=True),
        ),
    ]
