# Generated by Django 5.1.3 on 2025-01-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_expense_transaction_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='transaction_option',
            field=models.CharField(choices=[('bill', 'Bill'), ('voucher', 'Voucher'), ('gst', 'GST'), ('2_wheeler', '2-Wheeler'), ('4_wheeler', '4-Wheeler')], max_length=20, null=True),
        ),
    ]
