# Generated by Django 4.2.17 on 2025-09-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_advancegroup_leader_alter_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancegroup',
            name='leader',
        ),
        migrations.AddField(
            model_name='advancegroup',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
