# Generated by Django 5.1.3 on 2025-01-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_expense_transaction_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveyance',
            name='vehicle_type',
            field=models.CharField(choices=[('2_wheeler', '2_Wheeler'), ('4_wheeler', '4_Wheeler')], max_length=20),
        ),
    ]
