# Generated by Django 4.2.17 on 2025-09-08 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0023_remove_advancegroup_leader_advancegroup_is_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancegroup',
            name='is_leader',
        ),
        migrations.AddField(
            model_name='advanceassignment',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advancegroup',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_advance_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
