# Generated by Django 4.2.17 on 2025-09-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_advancegroup_is_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancegroup',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
