# Generated by Django 4.2.17 on 2025-09-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_advancegroup_remaining_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancegroup',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
