# Generated by Django 4.2.17 on 2025-04-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_advancepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashvoucher',
            name='proof_photo',
            field=models.FileField(blank=True, null=True, upload_to='cashvoucher_proofs/'),
        ),
    ]
