# Generated by Django 4.2.17 on 2025-04-04 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_cashvoucher_proof_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proofs/')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_photos', to='website.expense')),
            ],
        ),
    ]
