# Generated by Django 4.2.17 on 2025-09-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_advancegroup_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_allocation',
            field=models.BooleanField(default=False),
        ),
    ]
