# Generated by Django 4.2.17 on 2025-09-26 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0027_expense_is_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_voucher_number', models.CharField(max_length=50, unique=True)),
                ('item_type', models.CharField(choices=[('fright_transportation', 'Fright/Transportation'), ('food_grocery', 'Food/Grocery'), ('fuel_oil', 'Fuel and Oil'), ('others', 'Others'), ('vendor', 'Vendor'), ('reimbursement', 'Reimbursement'), ('site_services', 'Site Services'), ('advances', 'Advances'), ('travelling', 'Travelling'), ('electricity_bill', 'Electricity Bill'), ('internet_bill', 'Internet Bill'), ('postage_telegram', 'Postage and Telegram'), ('machine_repair', 'Machine Repair and Maintenance'), ('conveyance', 'Conveyance'), ('stationary_printing', 'Stationary and Printing'), ('hospitality', 'Hospitality'), ('medicine', 'Medicine')], max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('payment_category', models.CharField(choices=[('bill', 'Bill'), ('voucher', 'Voucher'), ('gst', 'GST'), ('2_wheeler', '2-Wheeler'), ('4_wheeler', '4-Wheeler')], max_length=20)),
                ('transaction_category', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20)),
                ('external_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card')], max_length=20)),
                ('proof_photo', models.FileField(blank=True, null=True, upload_to='directpay/proofs/')),
                ('transaction_date', models.DateField()),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
