# Generated by Django 4.2.17 on 2025-09-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_directpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directpay',
            name='e_voucher_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
