# Generated by Django 4.2.17 on 2025-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_directpay_e_voucher_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='directpay',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to='directpay/bills/'),
        ),
        migrations.AddField(
            model_name='directpay',
            name='gst_file',
            field=models.FileField(blank=True, null=True, upload_to='directpay/gst/'),
        ),
    ]
