# Generated by Django 4.2.17 on 2025-11-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_directpay_bill_file_directpay_gst_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancegroup',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('cheque', 'Cheque'), ('other', 'Other')], default='net_banking', max_length=50),
        ),
    ]
