# Generated by Django 4.2.17 on 2025-12-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_advancegroup_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossGroupAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_from', to='website.advancegroup')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='website.advancegroup')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_adjustments', to='website.payment')),
            ],
        ),
    ]
