# Generated by Django 4.2.17 on 2025-12-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_crossgroupadjustment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrossGroupAdjustment',
        ),
    ]
