# Generated by Django 4.2.17 on 2025-12-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_delete_crossgroupadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
