# Generated by Django 4.2.17 on 2026-01-13 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0037_mobilesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilesession',
            name='device_id',
        ),
        migrations.AlterField(
            model_name='mobilesession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
