# Generated by Django 4.2.17 on 2026-01-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_remove_mobilesession_device_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileSession',
        ),
    ]
