# Generated by Django 5.1.3 on 2024-12-17 05:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_closing_date', models.DateField()),
                ('workorder', models.FileField(blank=True, null=True, upload_to='workorders/')),
                ('boq', models.FileField(blank=True, null=True, upload_to='boqs/')),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedOrderFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foname', models.CharField(default='', help_text='Name associated with the follow-up', max_length=20)),
                ('fodate', models.DateField(help_text='Date of the follow-up')),
                ('fotime', models.TimeField(help_text='Time of the follow-up')),
                ('entrydate', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp for when this entry was created or modified')),
                ('confirmed_order', models.ForeignKey(help_text='The confirmed order associated with this follow-up', on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='Riva.confirmedorder')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='', max_length=30)),
                ('customername', models.CharField(default='', max_length=20)),
                ('companygst', models.CharField(default='', max_length=20)),
                ('companypan', models.CharField(default='', max_length=20)),
                ('refrence', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('location', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('1', 'HOT'), ('2', 'WARM'), ('3', 'COLD')], default='', max_length=20)),
                ('subproduct', models.CharField(default='', max_length=20)),
                ('closuredate', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='', max_length=100)),
                ('flag', models.TextField(blank=True, default='', max_length=200)),
                ('enqtype', models.CharField(default='', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_lost', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.executive')),
                ('files', models.ManyToManyField(blank=True, to='Riva.fileuploadmodel')),
                ('products', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Riva.products')),
            ],
        ),
        migrations.AddField(
            model_name='confirmedorder',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Riva.enquiry'),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foname', models.CharField(default='', help_text='Name associated with the follow-up', max_length=20)),
                ('fodate', models.DateField(help_text='Date of the follow-up')),
                ('fotime', models.TimeField(help_text='Time of the follow-up')),
                ('entrydate', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp for when this entry was created or modified')),
                ('enquiry', models.ForeignKey(blank=True, help_text='The enquiry associated with this follow-up', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='Riva.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('baseamount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('boq', models.FileField(blank=True, null=True, upload_to='boqs/')),
                ('finalamount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.enquiry')),
            ],
        ),
        migrations.AddField(
            model_name='confirmedorder',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotation'),
        ),
    ]
