# Generated by Django 4.2.17 on 2025-08-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='executive',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='executive',
            field=models.ManyToManyField(blank=True, to='Riva.executive'),
        ),
    ]
