# Generated by Django 5.1.3 on 2024-12-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xpredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('gst', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('terms_conditions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
