# Generated by Django 4.2.17 on 2025-08-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0002_remove_enquiry_executive_enquiry_executive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='executive',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='executive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Riva.executive'),
            preserve_default=False,
        ),
    ]
