# Generated by Django 5.1.3 on 2024-12-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0003_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hsncode',
            field=models.CharField(default='', max_length=30),
        ),
    ]
