# Generated by Django 4.2.17 on 2026-01-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0004_mobilesession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileSession',
        ),
    ]
