# Generated by Django 5.1.3 on 2024-12-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0004_products_hsncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
