# Generated by Django 5.1.3 on 2024-12-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0005_products_base_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=50)),
                ('quotation_no', models.CharField(max_length=50)),
                ('bill_to_company_name', models.CharField(max_length=255)),
                ('bill_to_customer_name', models.CharField(max_length=255)),
                ('bill_to_gst_number', models.CharField(max_length=20)),
                ('bill_to_address', models.TextField()),
                ('ship_to_company_name', models.CharField(max_length=255)),
                ('ship_to_customer_name', models.CharField(max_length=255)),
                ('ship_to_gst_number', models.CharField(max_length=20)),
                ('ship_to_address', models.TextField()),
                ('from_company_name', models.CharField(max_length=255)),
                ('from_phone', models.CharField(max_length=15)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_gst', models.CharField(max_length=20)),
                ('from_pan', models.CharField(max_length=20)),
                ('from_address', models.TextField()),
                ('bank_id', models.IntegerField()),
                ('terms_and_conditions', models.TextField()),
                ('item_details', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
