# Generated by Django 5.1.3 on 2024-12-17 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0006_commercialquote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialquote',
            name='bank_id',
        ),
        migrations.AddField(
            model_name='commercialquote',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Riva.bankdetails'),
            preserve_default=False,
        ),
    ]
