# Generated by Django 5.1.3 on 2024-12-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0007_remove_commercialquote_bank_id_commercialquote_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialquote',
            name='item_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
