# Generated by Django 5.1.3 on 2024-12-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0008_alter_commercialquote_item_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialquote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
