# Generated by Django 5.1.3 on 2024-12-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0009_alter_commercialquote_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialquote',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commercialquote',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
