# Generated by Django 5.1.3 on 2024-12-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0010_commercialquote_final_amount_commercialquote_margin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialquote',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='commercialquote',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='commercialquote',
            name='total_amount',
        ),
    ]
