# Generated by Django 5.1.3 on 2024-12-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0013_commercialquote_cgst_commercialquote_grandtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialquote',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='commercialquote',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='commercialquote',
            name='grandtotal',
        ),
        migrations.RemoveField(
            model_name='commercialquote',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='commercialquote',
            name='item_details',
        ),
        migrations.RemoveField(
            model_name='commercialquote',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='commercialquote',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='commercialquote',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='commercialquote',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='commercialquote',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='commercialquote',
            name='total_amount',
        ),
    ]
