# Generated by Django 5.1.3 on 2024-12-19 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0014_remove_commercialquote_cgst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsncode', models.CharField(default='', max_length=30)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quantity', models.PositiveIntegerField()),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('grandtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.products')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Riva.commercialquote')),
            ],
        ),
    ]
