# Generated by Django 5.1.3 on 2024-12-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0015_quotationitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='grandtotal',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='subtotal',
        ),
    ]
