# Generated by Django 5.1.3 on 2024-12-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0016_remove_quotationitem_grandtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='grandtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotation_no',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
