# Generated by Django 5.1.3 on 2024-12-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0018_commercialquote_cgst_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='grandtotal',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='subtotal',
        ),
    ]
