# Generated by Django 5.1.3 on 2024-12-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0019_remove_quotationitem_grandtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
