# Generated by Django 5.1.3 on 2024-12-31 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0022_confirmedorder_created_by_quotation_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('capacity', models.CharField(max_length=100)),
                ('total_needed_capacity', models.CharField(max_length=100)),
                ('waste_water_type', models.CharField(max_length=100)),
                ('total_no_machines', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KeyValueStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OutputTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('treated_water_characteristics', models.CharField(max_length=2000)),
                ('unit', models.CharField(max_length=100)),
                ('standard_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuotationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('suggestion', models.TextField()),
                ('proposal', models.TextField()),
                ('feat_advantages', models.TextField()),
                ('salient_feat', models.TextField()),
                ('dristi_subscription', models.TextField()),
                ('iot_hardware', models.TextField()),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.installationtable')),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_description_text', models.TextField()),
                ('etp_text', models.TextField()),
                ('stp_text', models.TextField()),
                ('shs_text', models.TextField()),
                ('automation_text', models.TextField()),
                ('footprint_area', models.TextField()),
                ('tentative_BOM', models.TextField()),
                ('output_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.outputtable')),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ParticularsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('particulars', models.CharField(max_length=2000)),
                ('first_year_exgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.AddField(
            model_name='outputtable',
            name='pd_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct'),
        ),
        migrations.CreateModel(
            name='OptionalHardwareTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('optional_hardware', models.CharField(max_length=2000)),
                ('qnty', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_exgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.AddField(
            model_name='installationtable',
            name='pd_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct'),
        ),
        migrations.CreateModel(
            name='Inclusions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance', models.TextField()),
                ('yearly_maintenance', models.TextField()),
                ('running_consumables', models.TextField()),
                ('exclusions', models.TextField()),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralTermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.CharField(max_length=1000)),
                ('flow_characteristics', models.CharField(max_length=1000)),
                ('trial_quality_check', models.TextField()),
                ('virtual_completion', models.TextField()),
                ('limitation_liability', models.CharField(max_length=1000)),
                ('force_clause', models.CharField(max_length=1000)),
                ('additional_works', models.CharField(max_length=1000)),
                ('warranty_guaranty', models.TextField()),
                ('arbitration', models.CharField(max_length=1000)),
                ('validity', models.CharField(max_length=1000)),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_eq', models.TextField()),
                ('instal_commissioning', models.TextField()),
                ('clients_scope', models.TextField()),
                ('note', models.CharField(max_length=100)),
                ('installation_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.installationtable')),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='AMC_Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_conditions', models.TextField()),
                ('installation_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.installationtable')),
                ('particulars_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.particularstable')),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('specification', models.CharField(max_length=1000)),
                ('qnty', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_exgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_cost_text', models.TextField()),
                ('terms_conditions', models.TextField()),
                ('installation_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.installationtable')),
                ('optional_hardware_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.optionalhardwaretable')),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
                ('specification_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.specificationtable')),
            ],
        ),
        migrations.CreateModel(
            name='SpecTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('specs_for_25kld', models.CharField(max_length=1000)),
                ('hidrec', models.CharField(max_length=1000)),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ReqSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_text', models.TextField()),
                ('process_diagram_text', models.CharField(max_length=1000)),
                ('process_diagram1', models.FileField(upload_to='process_diagrams/')),
                ('process_diagram2', models.FileField(upload_to='process_diagrams/')),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
                ('specs_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.spectable')),
            ],
        ),
        migrations.CreateModel(
            name='StandardTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('principal_purpose_unit_process', models.CharField(max_length=1000)),
                ('unit_processes', models.CharField(max_length=1000)),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('raw_sewage_characteristics', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_text', models.TextField()),
                ('standard_text', models.TextField()),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
                ('standard_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.standardtable')),
                ('table1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.table1')),
            ],
        ),
    ]
