# Generated by Django 5.1 on 2025-01-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0024_alter_amc_pricing_terms_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='companydetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
