# Generated by Django 5.1.3 on 2025-01-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0025_companydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputtable',
            name='standard_value',
            field=models.CharField(max_length=100),
        ),
    ]
