# Generated by Django 5.1.3 on 2025-01-08 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0026_alter_outputtable_standard_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentsPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotationproduct')),
            ],
        ),
    ]
