# Generated by Django 5.1.3 on 2025-01-13 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0027_contentspr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='entrydate',
        ),
        migrations.AddField(
            model_name='followup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup',
            name='enquiry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='Riva.enquiry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followup',
            name='fodate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='followup',
            name='foname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fotime',
            field=models.TimeField(),
        ),
    ]
