# Generated by Django 5.1.3 on 2025-01-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0029_confirmed_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedorderfollowup',
            name='confirmed_order',
            field=models.ForeignKey(help_text='The confirmed order associated with this follow-up', on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='Riva.confirmed_enquiry'),
        ),
    ]
