# Generated by Django 5.1.3 on 2025-01-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0030_alter_confirmedorderfollowup_confirmed_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmed_enquiry',
            name='quotation',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
