# Generated by Django 5.1.3 on 2025-01-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0031_alter_confirmed_enquiry_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmed_enquiry',
            name='quotation',
            field=models.CharField(max_length=40),
        ),
    ]
