# Generated by Django 5.1.3 on 2025-01-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0032_alter_confirmed_enquiry_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='revert_remarks',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='reverted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
