# Generated by Django 5.1.3 on 2025-01-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0033_enquiry_revert_remarks_enquiry_reverted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='revert_remarks',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='reverted_at',
        ),
    ]
