# Generated by Django 5.1.3 on 2025-01-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0034_remove_enquiry_revert_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevertRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revert_remarks', to='Riva.enquiry')),
            ],
        ),
    ]
