# Generated by Django 5.1.3 on 2025-01-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0035_revertremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_retrieved',
            field=models.BooleanField(default=False),
        ),
    ]
