# Generated by Django 5.1.3 on 2025-01-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0036_enquiry_is_retrieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='is_retrieved',
            new_name='is_reverted',
        ),
    ]
