# Generated by Django 5.1.3 on 2025-01-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0037_rename_is_retrieved_enquiry_is_reverted'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='revert',
            field=models.BooleanField(default=False),
        ),
    ]
