# Generated by Django 5.1.3 on 2025-01-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0038_confirmed_enquiry_revert'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='lost',
            field=models.BooleanField(default=False),
        ),
    ]
