# Generated by Django 5.1.3 on 2025-01-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0039_confirmed_enquiry_lost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmed_enquiry',
            old_name='lost',
            new_name='relegate',
        ),
    ]
