# Generated by Django 5.1.3 on 2025-01-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0040_rename_lost_confirmed_enquiry_relegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_relegated',
            field=models.BooleanField(default=False),
        ),
    ]
