# Generated by Django 4.2.17 on 2025-01-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0042_remove_enquiry_companygst_remove_enquiry_companypan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enqtype',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='refrence',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='subproduct',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
