# Generated by Django 4.2.17 on 2025-04-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0043_alter_enquiry_enqtype_alter_enquiry_refrence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedHidrecWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.IntegerField()),
                ('quotation_no', models.CharField(blank=True, max_length=50, null=True)),
                ('contents', models.TextField()),
                ('hidrec_wash_text', models.TextField()),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('carwash_text', models.TextField()),
                ('priceoil_skimmer', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.TextField()),
                ('terms_conditions', models.TextField()),
                ('general_maintenance', models.TextField()),
                ('total_price', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hidrec_wash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('hidrec_wash_text', models.TextField()),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('carwash_text', models.TextField()),
                ('priceoil_skimmer', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.TextField()),
                ('terms_conditions', models.TextField()),
                ('general_maintenance', models.TextField()),
                ('total_price', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
