# Generated by Django 4.2.17 on 2024-12-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_division_userprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
