# Generated by Django 4.2.17 on 2024-12-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('repair', models.BooleanField(default=False)),
                ('replacement', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.chemicalitem')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('repair', models.BooleanField(default=False)),
                ('replacement', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.electronicitem')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicPanelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('repair', models.BooleanField(default=False)),
                ('replacement', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.electronicpanel')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('visit_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('repair', models.BooleanField(default=False)),
                ('replacement', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.miscellaneousitem')),
            ],
        ),
        migrations.CreateModel(
            name='MOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('organize', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('meeting_chair', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.CharField(max_length=255)),
                ('meeting_conclusion', models.TextField()),
                ('summary_of_discussion', models.TextField()),
                ('attendees', models.JSONField(default=list)),
                ('apologies', models.JSONField(default=list)),
                ('agenda', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PumpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('repair', models.BooleanField(default=False)),
                ('replacement', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.pump')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('date_of_visit', models.DateField()),
                ('zone', models.CharField(choices=[('G', 'GKN'), ('C', 'CHP'), ('S', 'SRS')], max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('reason_of_visit', models.CharField(max_length=255)),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('other_remarks', models.TextField(blank=True, help_text='Store all other remarks concatenated.', null=True)),
                ('spares_details', models.TextField(blank=True, help_text='Concatenated spares details', null=True)),
                ('certified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('certified_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('date_of_complaint', models.DateField()),
                ('status_of_call', models.CharField(max_length=100)),
                ('chemical_items', models.ManyToManyField(through='apage.ChemicalItemStatus', to='apage.chemicalitem')),
                ('electronic_items', models.ManyToManyField(through='apage.ElectronicItemStatus', to='apage.electronicitem')),
                ('electronic_panels', models.ManyToManyField(through='apage.ElectronicPanelStatus', to='apage.electronicpanel')),
                ('miscellaneous_items', models.ManyToManyField(through='apage.MiscellaneousItemStatus', to='apage.miscellaneousitem')),
                ('pumps', models.ManyToManyField(through='apage.PumpStatus', to='apage.pump')),
            ],
            options={
                'verbose_name': 'Service Report',
                'verbose_name_plural': 'Service Reports',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WastewaterParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WastewaterParameterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('repair', models.BooleanField(default=False)),
                ('replacement', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.wastewaterparameter')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.servicereport')),
            ],
        ),
        migrations.CreateModel(
            name='ToolStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('remark', models.TextField(blank=True, null=True)),
                ('taken_status', models.BooleanField(default=False)),
                ('service_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.servicereport')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.tool')),
            ],
        ),
        migrations.AddField(
            model_name='servicereport',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apage.state'),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='wastewater_parameters',
            field=models.ManyToManyField(through='apage.WastewaterParameterStatus', to='apage.wastewaterparameter'),
        ),
        migrations.AddField(
            model_name='pumpstatus',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.servicereport'),
        ),
        migrations.AddField(
            model_name='miscellaneousitemstatus',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.servicereport'),
        ),
        migrations.CreateModel(
            name='MaintenanceChecklistAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='apage.maintenancechecklist')),
            ],
        ),
        migrations.CreateModel(
            name='MachineRunTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(max_length=255)),
                ('run_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('checked', models.BooleanField(default=False)),
                ('pass_status', models.BooleanField(default=False)),
                ('fail_status', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('service_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_times', to='apage.servicereport')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField()),
                ('point1', models.TextField()),
                ('point2', models.TextField()),
                ('point3', models.TextField()),
                ('point4', models.TextField()),
                ('notes', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.site')),
            ],
        ),
        migrations.AddField(
            model_name='electronicpanelstatus',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.servicereport'),
        ),
        migrations.AddField(
            model_name='electronicitemstatus',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.servicereport'),
        ),
        migrations.AddField(
            model_name='chemicalitemstatus',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.servicereport'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meetings/attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='apage.mom')),
            ],
        ),
    ]
