# Generated by Django 4.2.17 on 2025-08-16 07:12

import apage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='client_remark',
            field=models.TextField(blank=True, help_text='Remarks given by the client while signing.', null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='client_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports', to='apage.site'),
        ),
        migrations.AddField(
            model_name='site',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.zone'),
        ),
        migrations.AlterField(
            model_name='generalreport',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apage.site'),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='date_of_complaint',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='date_of_visit',
            field=models.DateField(blank=True, null=True, validators=[apage.models.no_future_dates]),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='reason_of_visit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='status_of_call',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports', to='app.zone'),
        ),
        migrations.CreateModel(
            name='SiteVisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateField()),
                ('next_due', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_schedules', to='apage.site', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='apage.servicereport')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
