# Generated by Django 4.2.17 on 2024-12-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mom',
            name='client',
        ),
    ]
