# Generated by Django 4.2.17 on 2024-12-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apage', '0002_remove_mom_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancechecklist',
            old_name='notes',
            new_name='observations',
        ),
        migrations.AddField(
            model_name='maintenancechecklist',
            name='current_load',
            field=models.CharField(blank=True, choices=[('checked', 'Checked'), ('repair', 'Repair'), ('replacement', 'Replacement')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maintenancechecklist',
            name='supply_voltage',
            field=models.CharField(blank=True, choices=[('checked', 'Checked'), ('repair', 'Repair'), ('replacement', 'Replacement')], max_length=20, null=True),
        ),
    ]
