# Generated by Django 4.2.17 on 2024-12-13 12:00

import apage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apage', '0003_rename_notes_maintenancechecklist_observations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalreport',
            name='date_of_visit',
            field=models.DateField(validators=[apage.models.no_future_dates]),
        ),
        migrations.AlterField(
            model_name='maintenancechecklist',
            name='visit_date',
            field=models.DateField(validators=[apage.models.no_future_dates]),
        ),
        migrations.AlterField(
            model_name='mom',
            name='date',
            field=models.DateField(validators=[apage.models.no_future_dates]),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='date_of_complaint',
            field=models.DateField(validators=[apage.models.no_future_dates]),
        ),
    ]
