# Generated by Django 4.2.17 on 2024-12-25 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apage', '0004_alter_generalreport_date_of_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereport',
            name='certified_by',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='certified_by_name',
        ),
        migrations.AddField(
            model_name='generalreport',
            name='edit_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancechecklist',
            name='edit_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancechecklistattachment',
            name='edit_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mom',
            name='edit_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='client_name',
            field=models.CharField(blank=True, help_text='Name of the client.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='client_signature',
            field=models.TextField(blank=True, help_text='Base64-encoded signature of the client.', null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='service_person_name',
            field=models.CharField(blank=True, help_text='Name of the service person.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='service_person_signature',
            field=models.TextField(blank=True, help_text='Base64-encoded signature of the service person.', null=True),
        ),
        migrations.CreateModel(
            name='ServiceReportEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_timestamp', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(max_length=255)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apage.servicereport')),
            ],
        ),
    ]
