# Generated by Django 4.2.17 on 2024-12-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apage', '0008_maintenancechecklist_user_servicereport_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalreport',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='maintenancechecklist',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='mom',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='servicereport',
            old_name='user',
            new_name='created_by',
        ),
    ]
