# Generated by Django 4.2.17 on 2024-12-26 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apage', '0009_rename_user_generalreport_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mom',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
