# Generated by Django 4.2.17 on 2024-12-26 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apage', '0010_mom_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mom',
            name='created_date',
        ),
        migrations.AddField(
            model_name='generalreport',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
