# Generated by Django 4.2.17 on 2025-01-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apage', '0012_mom_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancechecklist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
